cp -i /usr/share/texmf/tex/latex/ucs/contrib/cenccmn.tex .
cp -i /usr/share/texmf/tex/latex/adrconv/adrconv.tex .
cp -i /usr/share/texmf/tex/latex/adrconv/adrdir.tex .
cp -i /usr/share/texmf/tex/latex/adrconv/adrfax.tex .
cp -i /usr/share/texmf/tex/latex/adrconv/birthday.tex .
cp -i /usr/share/texmf/tex/latex/adrconv/email.tex .
cp -i /usr/share/texmf/tex/latex/base/docstrip.tex .
cp -i /usr/share/texmf/tex/latex/base/idx.tex .
cp -i /usr/share/texmf/tex/latex/base/lablst.tex .
cp -i /usr/share/texmf/tex/latex/base/latexbug.tex .
cp -i /usr/share/texmf/tex/latex/base/ltxcheck.tex .
cp -i /usr/share/texmf/tex/latex/base/nfssfont.tex .
cp -i /usr/share/texmf/tex/latex/base/sample2e.tex .
cp -i /usr/share/texmf/tex/latex/base/small2e.tex .
cp -i /usr/share/texmf/tex/latex/base/testpage.tex .
cp -i /usr/share/texmf/tex/latex/base/utf8-test.tex .
cp -i /usr/share/texmf/tex/latex/base/utf8test.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamerexample-foils.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamerexample-prosper.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamerexample-seminar.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamerexample-texpower.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamericonarticle.tex .
cp -i /usr/share/texmf/tex/latex/beamer/beamericonbook.tex .
cp -i /usr/share/texmf/tex/latex/carlisle/ltxtable.tex .
cp -i /usr/share/texmf/tex/latex/custom-bib/makebst.tex .
cp -i /usr/share/texmf/tex/latex/cyrillic/lcydefs.tex .
cp -i /usr/share/texmf/tex/latex/fp/fp.tex .
cp -i /usr/share/texmf/tex/latex/hyperref/hycheck.tex .
cp -i /usr/share/texmf/tex/latex/lucidabr/lucfont.tex .
cp -i /usr/share/texmf/tex/latex/mdwtools/doafter.tex .
cp -i /usr/share/texmf/tex/latex/seminar/2up.tex .
cp -i /usr/share/texmf/tex/latex/t2/test-utf8.tex .
cp -i /usr/share/texmf/tex/latex/textmerg/textmerg.tex .
cp -i /usr/share/texmf/tex/latex/tools/.tex .
cp -i /usr/share/texmf/tex/latex/tools/e.tex .
cp -i /usr/share/texmf/tex/latex/tools/fontsmpl.tex .
cp -i /usr/share/texmf/tex/latex/tools/h.tex .
cp -i /usr/share/texmf/tex/latex/tools/q.tex .
cp -i /usr/share/texmf/tex/latex/tools/r.tex .
cp -i /usr/share/texmf/tex/latex/tools/s.tex .
cp -i /usr/share/texmf/tex/latex/tools/verbtest.tex .
cp -i /usr/share/texmf/tex/latex/tools/x.tex .
cp -i /usr/share/texmf/tex/latex/vietnam/vncaps.tex .
cp -i /usr/share/texmf/tex/latex/html/techexplHTML.tex .
cp -i /usr/share/texmf/tex/latex/susebuch/doc/Befehle.tex .
cp -i /usr/share/texmf/tex/latex/susebuch/doc/versionen.tex .
cp -i /usr/share/texmf/tex/latex/susebuch/doc/docu.tex .
