#line 2 "lex_tab.c"

#line 4 "lex_tab.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qtm_table_output__create_buffer
#define yy_delete_buffer qtm_table_output__delete_buffer
#define yy_flex_debug qtm_table_output__flex_debug
#define yy_init_buffer qtm_table_output__init_buffer
#define yy_flush_buffer qtm_table_output__flush_buffer
#define yy_load_buffer_state qtm_table_output__load_buffer_state
#define yy_switch_to_buffer qtm_table_output__switch_to_buffer
#define yyin qtm_table_output_in
#define yyleng qtm_table_output_leng
#define yylex qtm_table_output_lex
#define yylineno qtm_table_output_lineno
#define yyout qtm_table_output_out
#define yyrestart qtm_table_output_restart
#define yytext qtm_table_output_text
#define yywrap qtm_table_output_wrap
#define yyalloc qtm_table_output_alloc
#define yyrealloc qtm_table_output_realloc
#define yyfree qtm_table_output_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qtm_table_output_restart(qtm_table_output_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qtm_table_output_leng;

extern FILE *qtm_table_output_in, *qtm_table_output_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qtm_table_output_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qtm_table_output_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qtm_table_output_restart()), so that the user can continue scanning by
	 * just pointing qtm_table_output_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qtm_table_output_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qtm_table_output_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qtm_table_output_wrap()'s to do buffer switches
 * instead of setting up a fresh qtm_table_output_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qtm_table_output_restart (FILE *input_file  );
void qtm_table_output__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qtm_table_output__create_buffer (FILE *file,int size  );
void qtm_table_output__delete_buffer (YY_BUFFER_STATE b  );
void qtm_table_output__flush_buffer (YY_BUFFER_STATE b  );
void qtm_table_output_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void qtm_table_output_pop_buffer_state (void );

static void qtm_table_output_ensure_buffer_stack (void );
static void qtm_table_output__load_buffer_state (void );
static void qtm_table_output__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qtm_table_output__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qtm_table_output__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qtm_table_output__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qtm_table_output__scan_bytes (yyconst char *bytes,int len  );

void *qtm_table_output_alloc (yy_size_t  );
void *qtm_table_output_realloc (void *,yy_size_t  );
void qtm_table_output_free (void *  );

#define yy_new_buffer qtm_table_output__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qtm_table_output_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qtm_table_output__create_buffer(qtm_table_output_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qtm_table_output_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qtm_table_output__create_buffer(qtm_table_output_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qtm_table_output_in = (FILE *) 0, *qtm_table_output_out = (FILE *) 0;

typedef int yy_state_type;

extern int qtm_table_output_lineno;

int qtm_table_output_lineno = 1;

extern char *qtm_table_output_text;
#define yytext_ptr qtm_table_output_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qtm_table_output_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qtm_table_output_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[82] =
    {   0,
        0,    0,   20,   18,    1,   12,    2,   18,   11,   17,
       14,   16,    1,    2,    0,   15,    0,    0,    0,    0,
       13,    0,   14,   16,   15,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
       13,   10,    6,    0,    0,   15,    0,    0,   15,    0,
        0,    0,    0,    0,    0,    0,   15,    0,   10,    0,
        0,    0,    4,    0,   10,   15,    0,    5,    8,    8,
        0,    0,   10,    0,    0,   10,    0,    9,    9,    9,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    6,    7,    6,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   10,   10,   11,   12,   10,
       10,   10,   10,   10,   10,   10,   13,   10,   10,   10,
       10,   10,   14,   15,   10,   10,   10,   10,   10,   10,
        1,    1,    1,    1,   10,    1,   16,   10,   10,   17,

       18,   10,   10,   10,   10,   10,   10,   19,   10,   20,
       21,   10,   10,   10,   10,   22,   10,   23,   10,   10,
       10,   10,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[24] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[88] =
    {   0,
        0,    9,  131,  132,   17,  132,   18,   18,  125,  120,
       16,    0,   24,   25,  123,  120,   25,   29,   31,   30,
       28,  117,   30,    0,  118,   39,   37,   42,   36,  132,
      103,   48,  114,  117,  112,   44,   57,   45,   98,  110,
      109,  108,  132,  111,   58,   59,   60,   99,  107,   50,
       95,  107,   92,  101,   51,   86,  101,  102,   97,  100,
       99,   94,  132,   93,   92,   93,   92,   89,   88,   87,
       86,   84,   81,   69,   68,   67,   66,   64,   63,   62,
      132,   79,   82,   64,   85,   88,   91
    } ;

static yyconst flex_int16_t yy_def[88] =
    {   0,
       82,   82,   81,   81,   81,   81,   81,   83,   81,   81,
       81,   84,   81,   81,   83,   81,   83,   83,   83,   81,
       81,   81,   81,   84,   81,   81,   83,   83,   83,   81,
       81,   81,   81,   81,   81,   83,   85,   83,   81,   81,
       81,   81,   81,   83,   83,   81,   83,   81,   81,   83,
       81,   83,   81,   81,   83,   81,   81,   81,   86,   83,
       81,   81,   81,   81,   86,   81,   81,   81,   81,   86,
       81,   81,   87,   87,   81,   87,   87,   81,   87,   87,
        0,   81,   81,   81,   81,   81,   81
    } ;

static yyconst flex_int16_t yy_nxt[156] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,    4,
        5,    6,    7,    8,    4,    9,   10,   11,   13,   14,
       14,   14,   16,   22,   23,   13,   14,   14,   14,   25,
       17,   18,   19,   25,   30,   25,   21,   22,   23,   32,
       25,   25,   27,   34,   31,   32,   25,   35,   25,   25,
       28,   29,   36,   40,   25,   25,   41,   38,   37,   15,
       47,   46,   25,   44,   25,   33,   24,   55,   50,   51,
       80,   79,   78,   60,   80,   79,   78,   77,   52,   12,
       12,   12,   15,   15,   15,   45,   45,   45,   64,   76,
       64,   75,   74,   75,   73,   70,   69,   68,   72,   71,

       70,   69,   68,   67,   66,   65,   63,   62,   61,   59,
       58,   57,   56,   54,   53,   49,   42,   41,   41,   48,
       35,   43,   42,   39,   33,   21,   26,   25,   21,   20,
       81,    3,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81
    } ;

static yyconst flex_int16_t yy_chk[156] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    5,    7,
        5,    7,    8,   11,   11,   13,   14,   13,   14,   17,
        8,    8,    8,   18,   20,   19,   21,   23,   23,   21,
       29,   27,   17,   26,   20,   21,   28,   26,   36,   38,
       18,   19,   27,   32,   50,   55,   32,   29,   28,   37,
       38,   37,   45,   36,   47,   46,   84,   50,   45,   46,
       80,   79,   78,   55,   77,   76,   75,   74,   47,   82,
       82,   82,   83,   83,   83,   85,   85,   85,   86,   73,
       86,   87,   72,   87,   71,   70,   69,   68,   67,   66,

       65,   64,   62,   61,   60,   59,   58,   57,   56,   54,
       53,   52,   51,   49,   48,   44,   42,   41,   40,   39,
       35,   34,   33,   31,   25,   22,   16,   15,   10,    9,
        3,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int qtm_table_output__flex_debug;
int qtm_table_output__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qtm_table_output_text;
#line 1 "lex_tab.l"
#line 2 "lex_tab.l"

#include <map>
#include <string>
#include <cstring>
#include <iostream>
#include <cstdlib>
#include <cstdlib>
#include <regex.h>
#include "const_defs.h"
#include "table_csv.h"

    /*
    typedef union YYSTYPE
    {


        int ival;
        double dval;
        char name[4095];
        char text_buf[4095];



    } YYSTYPE;


    YYSTYPE qtm_table_output_lval;

    enum {
        TABLE=1,
        PAGE,
        TOTAL,
        SIGMA,
        MEAN,
        STUB_FREQ,
        STUB_PERC
    };
    */


	extern int qtm_table_output_lex();
	extern void yyerror(const char * s);
	using std::cout;
	using std::cerr;
	using std::endl;
	using std::string;
	int qtm_line_no;
	int count_at_least_n_matches ( regmatch_t p_match[5]);
	void qtm_table_output_error(const char * s);
	string stub_text;


#define YY_NO_UNISTD_H 1
/*ID       [a-z][a-z0-9]*/
#line 591 "lex_tab.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int qtm_table_output_lex_destroy (void );

int qtm_table_output_get_debug (void );

void qtm_table_output_set_debug (int debug_flag  );

YY_EXTRA_TYPE qtm_table_output_get_extra (void );

void qtm_table_output_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *qtm_table_output_get_in (void );

void qtm_table_output_set_in  (FILE * in_str  );

FILE *qtm_table_output_get_out (void );

void qtm_table_output_set_out  (FILE * out_str  );

int qtm_table_output_get_leng (void );

char *qtm_table_output_get_text (void );

int qtm_table_output_get_lineno (void );

void qtm_table_output_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qtm_table_output_wrap (void );
#else
extern int qtm_table_output_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( qtm_table_output_text, qtm_table_output_leng, 1, qtm_table_output_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qtm_table_output_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qtm_table_output_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qtm_table_output_in))==0 && ferror(qtm_table_output_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qtm_table_output_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qtm_table_output_lex (void);

#define YY_DECL int qtm_table_output_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qtm_table_output_text and qtm_table_output_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "lex_tab.l"


#line 781 "lex_tab.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qtm_table_output_in )
			qtm_table_output_in = stdin;

		if ( ! qtm_table_output_out )
			qtm_table_output_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qtm_table_output_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qtm_table_output__create_buffer(qtm_table_output_in,YY_BUF_SIZE );
		}

		qtm_table_output__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qtm_table_output_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 82 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 81 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "lex_tab.l"
{
    /* ignore */
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "lex_tab.l"
{ /* ignore */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "lex_tab.l"
{
	cout << "RETURNING  EMPTY_LINE_1_COLS" << endl;
	return EMPTY_LINE_1_COLS;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 "lex_tab.l"
{
	cout << "RETURNING  BAN_TOTAL" << endl;
	return BAN_TOTAL;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "lex_tab.l"
{
	string side_total_str(qtm_table_output_text + 8);
	int side_total = atoi (side_total_str.c_str());
	cout << "RETURNING  SIDE_TOTAL:"
		<< "side_total_str:" << side_total_str << ", "
		<< "side_total: " <<side_total << endl;
	qtm_table_output_lval.ival = side_total;
	return SIDE_TOTAL;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "lex_tab.l"
{
	cout << "RETURNING EMPTY_LINE_2_COLS" << endl;
	return EMPTY_LINE_2_COLS;
}
	YY_BREAK
/*\"\",{DIGIT}+\.{DIGIT}+      */
case 7:
YY_RULE_SETUP
#line 101 "lex_tab.l"
{
	char * pos_2nd_dbl_quote = strrchr (qtm_table_output_text, '"');
	if (pos_2nd_dbl_quote) {
		string no (pos_2nd_dbl_quote + 2);
		double perc = atof (no.c_str());
		cout << "PERC: " << perc << endl;
		qtm_table_output_lval.dval = perc;
	} else {
		cerr << __LINE__
			<< ", "
			<< __FILE__
			<< ", "
			<< __PRETTY_FUNCTION__
			<< "Impossible ! lex condition is that there should be 2 quotes"
			<< endl;
	}
        cout << "got STUB_PERC " << qtm_table_output_text << endl;
	return STUB_PERC;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "lex_tab.l"
{
	string mean_str(qtm_table_output_text + 7);
	double mean = atof (mean_str.c_str());
	cout	<< "RETURNING  MEAN:"
		<< "mean_str:" << mean_str << ", "
		<< "mean: " << mean << endl;
	qtm_table_output_lval.dval = mean;
	return STUB_MEAN;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 131 "lex_tab.l"
{
	string stddev_str(qtm_table_output_text + 10);
	double stddev = atof (stddev_str.c_str());
	cout	<< "RETURNING  MEAN:"
		<< "stddev_str:" << stddev_str << ", "
		<< "stddev: " << stddev << endl;
	qtm_table_output_lval.dval = stddev;
	return STUB_STD_DEV;
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 141 "lex_tab.l"
{
	char * pos_2nd_dbl_quote = strrchr (qtm_table_output_text, '"');
	string no (pos_2nd_dbl_quote + 2);
	if (pos_2nd_dbl_quote) {
		string tmp = qtm_table_output_text;
		int pos_2nd_dbl_quote_int = tmp.rfind ('"');
		stub_text = tmp.substr (1, pos_2nd_dbl_quote_int-1);
		no = (pos_2nd_dbl_quote + 2);
	} else {
		cerr << __LINE__
			<< ", "
			<< __FILE__
			<< ", "
			<< __PRETTY_FUNCTION__
			<< "Impossible ! lex condition is that there should be 2 quotes"
			<< endl;
			exit(1);
	}
	//cout << "got STUB_FREQ: " << qtm_table_output_text << endl;
	if (strstr (qtm_table_output_text, "Sigma")) {
		double sigma = atof (no.c_str());
		qtm_table_output_lval.dval = sigma;
		cout << "SIGMA: " << "stub_text: "<< stub_text << " | " << sigma << endl;
		return SIGMA;
	} else {
		int freq = atoi (no.c_str());
		qtm_table_output_lval.ival = freq;
		cout << "STUB_FREQ: " << "stub_text: "<< stub_text << " | " << freq << endl;
		return STUB_FREQ;
	}
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 174 "lex_tab.l"
{
    //cout << "got COMMA" << endl;
    return COMMA;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 179 "lex_tab.l"
{
    ++qtm_line_no;
	//cout << "got a NEWL: qtm_line_no: "  << qtm_line_no << endl;
	return NEWL;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 185 "lex_tab.l"
{
		qtm_table_output_lval.dval = atof(qtm_table_output_text);
		cout << "got FNUMBER " << qtm_table_output_lval.dval << endl;
		return FNUMBER;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 191 "lex_tab.l"
{
		qtm_table_output_lval.ival = atoi(qtm_table_output_text);
		cout << "got INUMBER " << qtm_table_output_lval.ival << endl;
		return INUMBER;
	}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 198 "lex_tab.l"
{
		//int len_text=strlen(qtm_table_output_text);
		int len_text = qtm_table_output_leng;
		qtm_table_output_text[len_text-1]='\0'; // clobber double quote
		if(qtm_table_output_leng < MY_STR_MAX-1) {
			strcpy(qtm_table_output_lval.text_buf, qtm_table_output_text+1);
		} else {
			printf("TEXT TOKEN too long... exiting lexer\n");
			exit(1);
		}
		string text(qtm_table_output_lval.text_buf);
		if (strstr(text.c_str(), "#page")) {
			//cout << "RETURNING PAGE" << endl;
			return PAGE;
		} else if (strstr(text.c_str(),"Table ")) {
			cout << "RETURNING TABLE" << endl;
			return TABLE;
		} else if (strstr(text.c_str(),"Total")) {
			cout << "RETURNING TOTAL" << endl;
			return TOTAL;
		} else if (strstr(text.c_str(),"Mean")) {
			cout << "RETURNING MEAN" << endl;
			return MEAN;
		} else if (strstr(text.c_str(),"Sigma")) {
			cout << "RETURNING SIGMA" << endl;
			return SIGMA;
		} else if (strstr(text.c_str(),"Base:")) {
			cout << "RETURNING BASE_TEXT" << endl;
			return BASE_TEXT;
		} else {
			regex_t a_regex;
			regcomp (&a_regex, "^[a-zA-Z_][a-zA-Z0-9_]*$", 0);
			regmatch_t p_match[5];
			int n_match=5;
			int regex_result = regexec (&a_regex, text.c_str(), n_match, p_match, 0);
			if (regex_result == 0) {
				// we got a match
				int how_many_matches = count_at_least_n_matches (p_match);
				if (how_many_matches == 1) {
				// this is the start of a new table 
					cout << "RETURNING NAME: " << text << endl;
					return NAME;
				} else {
					cout << "RETURNING TEXT" << text << endl;
					return TEXT;
				}
			} else {
				cout << "RETURNING TEXT" << text << endl;
				return TEXT;
			}
		}
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 251 "lex_tab.l"
{
		if(qtm_table_output_leng < MY_STR_MAX) {
			strncpy(qtm_table_output_lval.name,qtm_table_output_text+1, qtm_table_output_leng-1);
            //cout << "got NAME:" << qtm_table_output_text << endl;
			return NAME;
		} else {
			printf("TEXT TOKEN too long... exiting lexer\n");
			exit(1);
		}
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 263 "lex_tab.l"
{
    //cout << "got DOT" << endl;
    //return DOT;
    return DOT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 269 "lex_tab.l"
{
    cout << "unhandled inputs: |" << qtm_table_output_text[0] << "|"
        << endl;
    return qtm_table_output_text[0];
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 275 "lex_tab.l"
ECHO;
	YY_BREAK
#line 1126 "lex_tab.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qtm_table_output_in at a new source and called
			 * qtm_table_output_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qtm_table_output_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qtm_table_output_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qtm_table_output_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qtm_table_output_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					qtm_table_output_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qtm_table_output_restart(qtm_table_output_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qtm_table_output_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 82 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 82 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 81);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qtm_table_output_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qtm_table_output_restart(qtm_table_output_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qtm_table_output_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qtm_table_output_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qtm_table_output_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qtm_table_output_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qtm_table_output__create_buffer(qtm_table_output_in,YY_BUF_SIZE );
	}

	qtm_table_output__init_buffer(YY_CURRENT_BUFFER,input_file );
	qtm_table_output__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qtm_table_output__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qtm_table_output_pop_buffer_state();
	 *		qtm_table_output_push_buffer_state(new_buffer);
     */
	qtm_table_output_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qtm_table_output__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qtm_table_output_wrap()) processing, but the only time this flag
	 * is looked at is after qtm_table_output_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qtm_table_output__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qtm_table_output_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qtm_table_output__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qtm_table_output_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qtm_table_output_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output__create_buffer()" );

	b->yy_is_our_buffer = 1;

	qtm_table_output__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qtm_table_output__create_buffer()
 * 
 */
    void qtm_table_output__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qtm_table_output_free((void *) b->yy_ch_buf  );

	qtm_table_output_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qtm_table_output_restart() or at EOF.
 */
    static void qtm_table_output__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qtm_table_output__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qtm_table_output__init_buffer was _probably_
     * called from qtm_table_output_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qtm_table_output__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qtm_table_output__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qtm_table_output_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qtm_table_output_ensure_buffer_stack();

	/* This block is copied from qtm_table_output__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qtm_table_output__switch_to_buffer. */
	qtm_table_output__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qtm_table_output_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qtm_table_output__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qtm_table_output__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qtm_table_output_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qtm_table_output_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qtm_table_output_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qtm_table_output__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qtm_table_output_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qtm_table_output__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qtm_table_output_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qtm_table_output__scan_bytes() instead.
 */
YY_BUFFER_STATE qtm_table_output__scan_string (yyconst char * yystr )
{
    
	return qtm_table_output__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qtm_table_output_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qtm_table_output__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qtm_table_output_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qtm_table_output__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qtm_table_output__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qtm_table_output__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qtm_table_output_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qtm_table_output_text[qtm_table_output_leng] = (yy_hold_char); \
		(yy_c_buf_p) = qtm_table_output_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qtm_table_output_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qtm_table_output_get_lineno  (void)
{
        
    return qtm_table_output_lineno;
}

/** Get the input stream.
 * 
 */
FILE *qtm_table_output_get_in  (void)
{
        return qtm_table_output_in;
}

/** Get the output stream.
 * 
 */
FILE *qtm_table_output_get_out  (void)
{
        return qtm_table_output_out;
}

/** Get the length of the current token.
 * 
 */
int qtm_table_output_get_leng  (void)
{
        return qtm_table_output_leng;
}

/** Get the current token.
 * 
 */

char *qtm_table_output_get_text  (void)
{
        return qtm_table_output_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qtm_table_output_set_lineno (int  line_number )
{
    
    qtm_table_output_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qtm_table_output__switch_to_buffer
 */
void qtm_table_output_set_in (FILE *  in_str )
{
        qtm_table_output_in = in_str ;
}

void qtm_table_output_set_out (FILE *  out_str )
{
        qtm_table_output_out = out_str ;
}

int qtm_table_output_get_debug  (void)
{
        return qtm_table_output__flex_debug;
}

void qtm_table_output_set_debug (int  bdebug )
{
        qtm_table_output__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qtm_table_output_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qtm_table_output_in = stdin;
    qtm_table_output_out = stdout;
#else
    qtm_table_output_in = (FILE *) 0;
    qtm_table_output_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qtm_table_output_lex_init()
     */
    return 0;
}

/* qtm_table_output_lex_destroy is for both reentrant and non-reentrant scanners. */
int qtm_table_output_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qtm_table_output__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qtm_table_output_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	qtm_table_output_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qtm_table_output_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qtm_table_output_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qtm_table_output_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qtm_table_output_free (void * ptr )
{
	free( (char *) ptr );	/* see qtm_table_output_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 275 "lex_tab.l"




	//void yyerror(const char * s)
	void qtm_table_output_error(const char * s)
	{
		//fprintf(stderr, "reached here: %s\n", __PRETTY_FUNCTION__);
		//using qscript_parser::no_errors;
		//using qscript_parser::qtm_line_no;
		//++no_errors;
	 	printf("%s: line: %d: qtm_table_output_text: %s\n", s, qtm_line_no, qtm_table_output_text);
	 	printf("line: %d: \n", qtm_line_no);
		//printf ("lexical error: line: %d, column: %d\n"
		//	, lex_location.lineNo_
		//	, lex_location.columnNo_);
		//printf ("%s\n", lex_location.currentLine_.str().c_str());
		//printf ("%*s\n%*s\ntoken: %s\n", lex_location.columnNo_, "^"
		//		    , lex_location.columnNo_, s, qtm_table_output_text);
	}


//int qtm_table_output_wrap()
int qtm_table_output_wrap()
{
	return 1;
}

// 
int count_at_least_n_matches ( regmatch_t p_match[5])
{
	int n_matches = 0;
	for (int i= 0; i< 5; ++i) {
		if (p_match[i].rm_so != -1) {
			++ n_matches;
		}
	}
	return n_matches;
}

	/*
	int main ()
	{
		std::string fname ("T.CSV");
		FILE * qtm_table_output_in = fopen(fname.c_str(), "rb");
		qtm_table_output_restart(qtm_table_output_in);
		int n_loops = 0;
		while (qtm_table_output_lex()) {
			++ n_loops;
		}
		cout << "EXIT: " << n_loops << endl;
	}
	*/


