/*
 * =====================================================================================
 *
 *       Filename:  EvalReturnValue.h
 *
 *    Description:  Return Data Type for the Eval2 Return function generated by the
 *    		    compiler
 *
 *        Version:  1.0
 *        Created:  Friday 06 September 2013 06:04:49  IST
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Neil DSouza
 *
 * =====================================================================================
 */

#ifndef QScriptEvalReturnValue_h
#define QScriptEvalReturnValue_h

struct AbstractRuntimeQuestion;
struct EvalReturnValue {
	vector<string> errMessageVec_;
	vector<AbstractRuntimeQuestion*> qVec_;
};

#endif /*  QScriptEvalReturnValue_h */
